 const data = [
    {
      code: 'ABC',
      name: 'Company ABC',
      currency: 'USD',
      marketCap: 500,
      priceNetVariation: '+2.5%',
      changePercentage: '+1.8%',
      relatedNews: 'Lorem ipsum dolor sit amet',
      type: 'Public',
    },
    {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
      {
        code: 'ABC',
        name: 'Company ABC',
        currency: 'USD',
        marketCap: 500,
        priceNetVariation: '+2.5%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
    {
        code: 'BXm',
        name: 'Company ABC',
        currency: 'IBM',
        marketCap: 500,
        priceNetVariation: '+2.7%',
        changePercentage: '+1.8%',
        relatedNews: 'Lorem ipsum dolor sit amet',
        type: 'Public',
      },
    // Add more data objects here as needed
  ];

  export {data}